language: csharp

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      dotnet: 1.0.1
      mono: none
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.1
      mono: none

branches:
  only:
    - master
script:
  - ulimit -n 2048
  - dotnet restore "src\GB2260" 
  - dotnet build "src\GB2260"
  - dotnet restore "test\GB2260.Test"
  - dotnet test "test\GB2260.Test"