version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
install:
- cmd: git submodule update --init --recursive
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\src\GB2260\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: Wrq+QibneTq9Rvutd75Y7Hvf+UcJ3K/RA/cl1Eb4ViymauThEu1/g22002Bx4MHn
  on:
    appveyor_repo_tag: true