version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: k+323/6hqQuYB4EzqreswA51buEG/ZrZJQ0BrQJtf19PFr2V1ri0lp1brWT7spb2
install:
- cmd: git submodule update --init --recursive
build_script:
- ps: .\Build.ps1
test_script:
- dotnet test test/GB2260.Test/GB2260.Test.csproj --configuration Release -f netcoreapp1.1 --no-build
- bash coverage.sh
- bash coveralls.sh
artifacts:
- path: .\src\GB2260\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: Wrq+QibneTq9Rvutd75Y7Hvf+UcJ3K/RA/cl1Eb4ViymauThEu1/g22002Bx4MHn
  on:
    appveyor_repo_tag: true